### ISSUE TITLE
allow authentication strategy overrides for increased extensibility

### ISSUE THREAD

**Issue by adamsachs** [ethyca/fidesops#1003]
### Is your feature request related to a specific problem?

https://github.com/ethyca/fidesops/issues/562 describes a general effort/approach to making `fidesops` factories more extensible, so that developers outside of the core `fidesops` codebase can develop their own implementations that plug into the core factory.

we decided to break up that issue into sub-issues for each specific factory that we'd like to refactor (pun not intended). this issue covers the **authentication strategy factory**.

this will also, in effect, give us a mechanism for providing _override_ escape hatches for SaaS auth mechanisms, just as we did for SaaS request execution in https://github.com/ethyca/fidesops/issues/815. 

### Describe the solution you'd like

- i think we can follow a similar approach to what was done in https://github.com/ethyca/fidesops/pull/560 for the masking strategy factory. custom implementations can register themselves using a decorator, and no updates need to be made to the core fidesops codebase.
- these  "custom" authentication implementations will register themselves with a given name/ID, and that will need to be referenced in the `client_config.authentication.strategy` field of the SaaS config. The implementations will be able to define their own `configuration` class/model, similar to how it works with the masking strategy factory in https://github.com/ethyca/fidesops/pull/560

### Additional context

-

**Comment by adriaaaa** [comment]
Adam will let us know if we should keep this ticket separate from the refactoring factories ticket by the end of the day today.

Other info:
this is a N2H, we can leverage our current pattern for now.

**Comment by adamsachs** [comment]
closing because the functionality will be covered as part of https://github.com/ethyca/fidesops/issues/562, which refactors all strategy factories into a single unified factory that allows for improved extensibility.
