### ISSUE TITLE
Create `AuditLog` event on `PrivacyRequest` approval

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#1021]
When `PrivacyRequest`s are approved by a user, we should be automatically created an approval event in the `AuditLog` table.

## Questions
- what should happen when privacy requests are automatically approved? Do we create an audit log no pointing to any specific user, or do we not create one at all?

**Comment by sanders41** [comment]
>what should happen when privacy requests are automatically approved? Do we create an audit log no pointing to any specific user, or do we not create one at all?

What I have seen done in other audit logs in this situation is the "user" is listed as `system`

**Comment by adriaaaa** [comment]
+1 to paul's response.
