### ISSUE TITLE
Create `AuditLog` event when requests finish processing

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#1022]
When a `PrivacyRequest` finishes executing successfully, Fidesops should create an `AuditLog` event to mark the same time as `PrivacyRequest.finished_processing_at`

## Questions
- should we also create execution log events for other `PrivacyRequest.status` transitions? If so, maybe this is best implemented as a listener on the `PrivacyRequest` model rather than in the request's execution.

### Notes
* consider putting in auditlog instead with system user.

**Comment by pattisdr** [comment]
ExecutionLogs currently require a collection_name though -
