### ISSUE TITLE
Add a Connector - SaaS Dataset Management (YAML method)

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fidesops#1090]
### Description

This work is to provide a way for someone to manage (ethyca-built) saas connector datasets and references between datasets in the UI.

### Assumptions

- this is for ethyca built saas connectors.
- the ctl team has already implemented something similar for datasets. let's refer to their work here for consistency.
- there should not be a "Add another dataset" option in this flow.
- for YAML validation, let's see what ctl team did and then we can consider including our validation endpoints or creating a spike ticket to do this research.

### Acceptance Criteria

1. Demonstrate that a user can navigate to the dataset configuration section of a SaaS connector
2. Demonstrate that a user can:
-- see the defaulted dataset and config YAML that ethyca has provided for that connector
-- modify the YAML and save the changes
-- clear out the existing YAML and replace it
3. Confirm that a log is generated every time someone saves the YAML dataset.

### Mockups
Can use these mocks, but will be slightly tweaked (refer to AC above): [Figma](https://www.figma.com/file/NeFvOOb1RT2fcdqZT0vBF2/Fidesctl-Management-UI?node-id=2670%3A43598)

**Comment by adriaaaa** [comment]
@chriscalhoun1974 to reach out to ctl team to ask questions so we can point properly tomorrow.

**Comment by chriscalhoun1974** [comment]
@ethyca/fidesctl-team Good morning! In Fidesctl UI, is there existing feature functionality which allows a user to upload a YAML file? In addition, does the user have the ability to copy/paste and edit the given YAML file through an editor within the browser? Is the YAML editor provided by NPM package [js-yaml](https://github.com/nodeca/js-yaml)? 

We are looking to provide this feature to allow a user to upload their Dataset Configuration YAML file. Is there anyone from the Fidesctl team which I can further discuss this feature with? Look forward to hearing your feedback. Thank you for your assistance.

**Comment by chriscalhoun1974** [comment]
@allisonking Most definitely! Thanks for your help. I will reach out if I have anymore questions.

**Comment by chriscalhoun1974** [comment]
@adriaaaa Can you please provide user instruction content for the `Dataset configuration` page? Thank you.

![Image](https://user-images.githubusercontent.com/68459950/185645022-f31cfadb-d4e9-4cbc-8782-bc66fba15aef.png)

**Comment by adriaaaa** [comment]
@chriscalhoun1974 you can use this: "View your system yaml below! You can also modify the yaml if you need to assign any references between datasets."
