### ISSUE TITLE
Add default HTML template for notification emails

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#1157]
Let's make a basic template (that can be improved upon later) to house the notification emails for Fidesops. We can use a similar technique that we used for the Subject Identity Verification email template.

## Questions
- how do we handle styling?
  - email providers block external CSS files so let's put any CSS in the template directly

**Comment by eastandwestwind** [comment]
Complete in https://github.com/ethyca/fidesops/pull/1282. We will add a new template for each notification type
