### ISSUE TITLE
Consent database updates

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#1160]
### Description

This PR describes the changes required to the Fidesops application DB in order to store consent preferences for data subjects.

### Acceptance Criteria

1. Add the following table to the DB:

```
Consent
- identity: ProvidedIdentity
- regulation: Enum(gdpr, ccpa, ...)  # This should be optional
- data_use: string  # once we unify Fides this will map to custom data uses created in Fidesctl
- data_use_description: string  # something we can use to describe a human readable version of what this use case _is_
- opt_in: bool
```

**Please note that all models should inherit from the FidesBase, which will also provide utility fields such as `uuid`, `created_at`, etc**

2. Make `ProvidedIdentity.privacy_request_id` a nullable field.
3. Update `ProvidedIdentity.hash_value()` to use no salt when hashing identities for consent purposes.
4. Update the `get_request_status` API view to exclude any `ProvidedIdentity`s where `privacy_request_id` is `null`.

**Comment by sanders41** [comment]
> Update ProvidedIdentity.hash_value() to use no salt when hashing identities for consent purposes.

@seanpreston does this mean that it should hash with salt in some cases and not others, or never hash with salt?

**Comment by seanpreston** [comment]
Hey @sanders41 — this looks like an out-dated requirement. Fidesops uses a [static salt](https://github.com/ethyca/fidesops/blob/main/src/fidesops/ops/models/privacy_request.py#L725) right now when hashing provided identities that isn't configurable.

We ought to make that configurable in the future and re-assess this however. My concern at the time was that we'd have a way to find the identity again in the event the consent preferences were to be updated.
