### ISSUE TITLE
[Spike] Improvements to the external integration test harness

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#117]
High quality external integrations are key to the success of Fidesops as a product. The process for testing one of these as it stands is:

- Create external datastore / schema
- Create dataset file
- Create `ConnectionConfig` + `DatasetConfig` fixtures
- Add comprehensive data
  - e.g. data that invokes edge cases in the traversal — table joins across dataset FKs
  - e.g. any datastore specific edge cases like `VARIANT` in Snowflake, `geo` in Postgres
  - e.g. array type columns
- Run access requests — assert the correct data is retrieved
- Run erasure requests — assert the data in the underlying datastore has been erased
  - We need to do this for every permutation of data type + masking strategy supported by that datastore
  - Restore data after each erasure so the full dataset can always be tested
- Teardown datastore / schema

There's a lot of work in that full process — any and every piece that can be automated should be automated.

We should think about Pytest markers for each external datastore — a nested structure like:
```
@pytest.marker.external_integration.snowflake
@pytest.marker.external_integration.redshift
```
could work quite well, as it gives us granularity on what we want to run and when. Running large tests through these data stores will get costly in terms of time, so we'll want to be as efficient as possible.

This is largely not for performance testing, it's for *compatibility* testing.

**Comment by NevilleS** [comment]
This looks about right to me and I agree - the best thing we can do for a lot of features is to start from representative example schemas in a particular flavour of DB, so if we make it really easy to add edge cases to a core suite of functionality we'll get a lot of benefit from this.

Right now most of the integration test data is established via SQL using Docker scripts, but moving that setup/teardown into Python code would be an improvement.
