### ISSUE TITLE
Plaid

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fidesops#1185]
API docs -> https://plaid.com/docs/
Request Form: Access/Delete Request -> https://plaid.com/legal/data-protection-request-form/

**Comment by Kelsey-Ethyca** [comment]
According to Plaid's website the free account should have everything we need! 
> By creating a free account, you can:
> Access our bank data APIs, which include bank account info and transaction data
> Use sample data to try out our APIs in our sandbox environment
> Use real data from up to 100 real financial accounts when you're ready to start building

**Comment by Kelsey-Ethyca** [comment]
https://start.1password.com/open/i?a=5LPILPRDUBGWBPJWYS6QHHHLRE&v=j5rloag3ijafxntkpw5wct23dy&i=rju7uzh3lciupl4rbm6k6yunjy&h=ethyca.1password.com

**Comment by Zeeshan-Ethyca** [comment]
[https://share.1password.com/s#fCeXdpPqIMvOOkeexppngIyZbOy_RO-S1dJCR2W1_HM](https://share.1password.com/s#fCeXdpPqIMvOOkeexppngIyZbOy_RO-S1dJCR2W1_HM)
