### ISSUE TITLE
[Array + JSON handling] Erasures in complex datatypes for MongoDB

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#129]
Add support for erasing data from complex datatypes (objects + arrays) in MongoDB.

**Comment by pattisdr** [comment]
Note access requests addressed here https://github.com/ethyca/fidesops/pull/165 and some light testing of nested erasures completed. This ticket should make sure there are no other additional requirements we need to consider and complete more detailed testing.

**Comment by pattisdr** [comment]
FYI Current mongo work that I'm doing for accessing data in complex arrays involves a design for erasures, this is being looked at currently.
