### ISSUE TITLE
Create default policies automatically on Fidesops setup

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#1309]
One barrier to setting up Fidesops is Policy creation, to mitigate this we can optionally include some default policies based on a config. var `FIDESOPS__DATABASE__CREATE_DEFAULT_POLICIES`. The policies should be:

- `download`: an access policy targeting all data under the `user` datacategory, using the local StorageConfig
- `delete`: an erasure policy targeting all data under the `user` datacategory, using the `HASH` type and `SHA-512` strategy.

**Comment by pattisdr** [comment]
How will we reconcile with the very similar work that adds default policies to the database as a migration? https://github.com/ethyca/fidesops/blob/main/src/fidesops/ops/migrations/versions/55d61eb8ed12_add_default_policies.py
