### ISSUE TITLE
[Spike] TimescaleDB

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fidesops#1311]

**Comment by malaethyca** [comment]
We are blocked on onboarding Snackpass for this connector to be delivered.

**Comment by NevilleS** [comment]
Some research notes from me:
* Docs for TimescaleDB are all here: https://docs.timescale.com/
* It's a fully PostgreSQL-compatible database, so our existing Postgres connector is likely going to work as-is. In that sense, it's very similar to MariaDB (which is a specialization of MySQL): https://docs.timescale.com/timescaledb/latest/overview/
* We should still set up some tests to be sure. They distribute an OSS docker image here: https://docs.timescale.com/install/latest/installation-docker/

Even though this should _largely_ just be a matter of testing our Postgres connector against Timescale, I'd assume a few things should get done here:
* An admin should be able to view TimescaleDB in the Admin UI as an available connector
* An admin should be able to configure TimescaleDB in the Admin UI and test the connection
* An admin should be able to upload their dataset for TimescaleDB in the Admin UI
* An engineer should be able to do all of the above via the API
* (in other words: this should work exactly like Postgres)

Hopefully that helps a bit! Let us know if anything is surprising or difficult here or what else you might need.
