### ISSUE TITLE
Firebase Authentication

### ISSUE THREAD

**Issue by Kelsey-Ethyca** [ethyca/fidesops#1332]

**Comment by Kelsey-Ethyca** [comment]
Wee have a pro adaptor for this https://gitlab.com/ethyca/adaptors/-/blob/master/src/main/resources/integrations/generic/firebase.yaml

**Comment by galvana** [comment]
The pro adaptor only retrieves Firebase user information, but Firebase is a database itself. We should follow up on this request and verify if all we need is to retrieve the user information like we did before or approach this in a more generic way and treat this like one of our other Fidesops database connectors.

**Comment by NevilleS** [comment]
This is actually a bit confusing, but **Firebase** itself is an "app development platform", and within that platform are a couple of products like:
* Cloud Firestore (fully cloud database: https://firebase.google.com/products/firestore)
* Realtime Database (previous version of their database: https://firebase.google.com/products/realtime-database)
* Authentication (SaaS API for handling authn flows: https://firebase.google.com/products/auth)
* etc.

In this case, we're focused on the "Firebase Authentication" product, which is focused exclusively on just the user authentication APIs. You can see more here: https://firebase.google.com/docs/reference/rest/auth

**Comment by adamsachs** [comment]
noting here that Firebase Auth offers an [Admin SDK](https://firebase.google.com/docs/auth/admin) (with python support) that _seems_ like the recommended way of [managing users](https://firebase.google.com/docs/auth/admin/manage-users), which i believe is what we are looking to do here (the first use case they describe is ["retrieve user data"](https://firebase.google.com/docs/auth/admin/manage-users#retrieve_user_data)). i want to bring up the _possibility_ of using a SaaS request override extension here to bypass the normal HTTP SaaS connector framework. adding a dependency on that SDK would be something we need to think hard about, but one potential mitigating course would be to implement the extension/override in the `-plus` product.

the reason i'm bringing up this potential path is that the [REST APIs for user management](https://firebase.google.com/docs/reference/rest/auth#section-get-account-info) seem to rely on having a user's `idToken`, which is an ephemeral token generated by [signing in with the user's `customToken`](https://firebase.google.com/docs/reference/rest/auth#section-verify-custom-token), and i haven't been able to totally pin down how _that's_ generated - although it too can seemingly be [done by the SDK](https://firebase.google.com/docs/auth/admin/create-custom-tokens). generating the `customToken` and using that to retrieve an ephemeral `idToken` does seem to be exactly the course that the legacy adaptor took, although it relies on a `FirebaseCustomTokenGenerateFunction` to generate that customToken, and i haven't been able to find that function's implementation with my limited knowledge of the pro/adaptors codebase. generally, although this path seems like it _may_ be feasible in fidesops, it's looking to me like it will also require some extension/overrides of the generic framework and potentially even a dependency on the SDK -- but i could be off-base on that. if that is the case, though, perhaps we are better off just bypassing the HTTP API altogether and using a simple ```user = auth.get_user_by_email(email)``` from the admin SDK.

my understanding here - of the use case, the firebase landscape, and our legacy implementation - is still very shaky at best, so these are more just thoughts i wanted to jot down before we head into the weekend and look to tackle this next week.

**Comment by adamsachs** [comment]
here's an [internal "design doc"](https://ethyca.atlassian.net/wiki/spaces/EN/pages/2475786259/Fidesops+Firebase+Auth+Integration+Design) (rough term) i've published with initial findings/questions/assumptions. there is more detail in the doc, but the two fundamental decisions for implementation are:
- do we use the firebase admin SDK or do we use the REST API for integration?
- what approach do we take for service-account auth?

i'll look to draft up prototypes for both the admin SDK and the REST API approach - both should be feasible. i'll make some assumptions about the service-account auth for now, that should be relatively easy to swap in/out later.
