### ISSUE TITLE
UberEats - Access

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fidesops#1353]

**Comment by Kelsey-Ethyca** [comment]
Need creds from Kelsey (CK) 
Blocked by https://github.com/ethyca/fidesops/issues/1390

**Comment by Kelsey-Ethyca** [comment]
This will have to be a manual connector setup by the customer. Ubereats has no api or email. A [form](https://help.uber.com/riders/article/privacy-request-form-for-business-customers-and-partners?nodeId=2d3d448a-0697-4c0e-b235-da26f5b84963) most be filled out.
