### ISSUE TITLE
Move from `setup.cfg`, `setup.py`, `MANIFEST.in`, and `requirements.txt` to `pyproject.toml`.

### ISSUE THREAD

**Issue by wiseaidev** [ethyca/fidesops#1415]
### Is your feature request related to a specific problem?

Hey fellas! As you may already know, the use of `setup.cfg`, `setup.py`, `MANIFEST.in`, and `requirements.txt` files is quite [outdated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html). Because of [PEP 517](https://peps.python.org/pep-0517/), [PEP 660](https://peps.python.org/pep-0660/), and [PEP 631](https://peps.python.org/pep-0631/), the packaging is now being standardized on the usage of the `pyproject.toml` file.

### Describe the solution you'd like

Given the above info, I am going to spend some time updating the project packaging to support `pyproject.toml`, and ultimately add support for `poetry`(optional).

### Describe alternatives you've considered if any

Not available.

### Additional context

That's pretty much it. What do you think?

**Comment by NevilleS** [comment]
Hi @wiseaidev and thanks for the contributions! We'd be happy to consider this enhancement, just one issue - we're currently in the process of migrating this project into our other repo, `fides`, to unify these two tools together. You can see the prerelease branch here: https://github.com/ethyca/fides/tree/unified-fides-2

If it works for you, can you reopen this issue and open a PR on that project instead? You'll find that the general layout is similar so any of the coding you've done so far should be highly compatible.

Thanks!

**Comment by wiseaidev** [comment]
Hey @NevilleS, thanks for the reply. I will have a look at that project and see what I can contribute to it.

**Comment by NevilleS** [comment]
Great, thanks! I'd be happy to answer questions or set you up for more. If you join our Slack community at fi.des/slack you can chat me there too!

**Comment by ThomasLaPiana** [comment]
@wiseaidev Thanks for your suggestion/contribution! I'd be happy to review a PR! This is something we've been slowly moving to (`pyproject.toml`) but haven't prioritized. As long as all of our functionality remains and it doesn't complicate future development, I'm happy to have it!

**Comment by wiseaidev** [comment]
Hey folks, thanks for the replies. The challenging part for me here is to figure out how `python-versioneer` works cause this is the first time I stumbled across this package. Usually, I use `bump2version` for package versioning.

**Comment by sanders41** [comment]
@wiseaidev does [this](https://github.com/python-versioneer/python-versioneer/blob/master/INSTALL.md#common-steps) help with your versioneer questions?

**Comment by wiseaidev** [comment]
closing in favour of fides#129.
