### ISSUE TITLE
DB ExecutionLogs should only print affected data categories for erasures

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fidesops#144]
Born from the discussion on #38 , we found that `fields_affected` in the logs includes `data_categories` that were not specified on the erasure rule. This is misleading and incorrect. 

The logs `fields_affected` should only output categories that were, in fact, masked by fidesops.  This issue should correct the log output and for any other place that the logs incorrectly print what was affected, correct that as well.

**Comment by pattisdr** [comment]
Note, these are the ExecutionLogs that are written to the db-
