### ISSUE TITLE
[Array + JSON Handling] Document nested object and array formats in the Dataset

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#147]
We should add something more comprehensive to the docs for supported `data_type: ...` annotation in the `fidesops_meta:` section of the dataset too.

We currently have a short section describing the datatypes available towards the bottom of this page: https://ethyca.github.io/fidesops/guides/datasets/. These datatypes probably now deserve their own page.

**Comment by pattisdr** [comment]
I've added some partial documentation for objects, but will add document this better as part of my work in https://github.com/ethyca/fidesops/issues/146, https://github.com/ethyca/fidesops/issues/129
