### ISSUE TITLE
[SaaS Connector Engine] Define connection_test implementation

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fidesops#171]
**Description**
Each connector to a third party app should have a method to call test a connection. We need to create a way where we can programmatically test the logic against the schema. 

**Acceptance Criteria**
1. Demonstrate that a user can perform a connection test for a SaaS Connector.
2. Show that we allow the ability to intake Authorization header and query params

**Additional Information**
This iteration must support the following authentication methods:
- Basic auth
- Bearer auth

Choose one or all of the following 3rd party applications to perform a connection test on Stripe, Zendesk, Slack (can pick something else if any connection test appears to be "off-standard")

**Comment by nschoenbrot** [comment]
Hi @adriaaaa. 

I wanted to clarify what is meant by "API Token". Both Basic and Bearer are registered HTTP Authentication Schemas, but "API Token" is not. See: https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml 

We can pass an "API Token" via the Authorization header using the Bearer schema. Would that be sufficient?

**Comment by adriaaaa** [comment]
Spoke with @nschoenbrot and @galvana and updated the description
