### ISSUE TITLE
[Privacy Center UI] A basic Privacy Center UI, v0

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#228]
We want to explore a frictionless deployment "privacy center" solution that takes in privacy requests such as Access requests, Deletion requests, and Rectification requests.

## Requirements:

Step 1: developer user is able to pull down project without having FE deployment knowledge

- ShOPP must be built using Vercel and NextJS
- ShOPP must be trivially deployable
- ShOPP must be a static site with minimal UI configurability

Step 2: developer user is able to do a one-line deployment of the privacy center to a desired location 

- Developer user is able to build the ShOPP application with the command `create-privacy-portal`.  User is shown logs of the process and settings.
- Developer user is able to easily deploy the privacy center following the best practices of NextJS apps.

Step 3: developer user is able to minimally customize certain components on the privacy center after deployment

- User must be able to configure ShOPP application settings with easy to use/maintain file format (ie: JSON or API/web service call). This file must have config options for:
  - Page Title: Default label “Your Privacy Center” 
  - Privacy Actions: Access, Delete, Rectification 
  - Privacy Action Labels: “Download Your Data”, “Delete Your Data”, “Edit Your Data”
  - Privacy Action Icons: point to directory 
  - Identity string input: mapping to a fidesops identity type, select n-number of identity string inputs
  - Policy keys: One for access, one for erasure
  - User must be able to configure custom styling via css that the user can modify or import after deployment
  - User must be able to customize or swap default assets and text strings
  - User must be able to save changes or updates to configurations

```
{
    "title": "my privacy centre",
    "fidesops_host": "https://...",
    "actions": [
        {
            "label": "erase my data",
            "policy_key": "my_erasure_policy",
            "icon_path": "my_icon.png",
            "identity_inputs": ["email", "phone"]
        }, {
            ...
        }
    ],
}
```

Step 4: data subject user enters subject request

- User must be able to visit a publicly deployed webpage
- User must be able to enter some identifying information, such as an email address
- User must be able to select a type of privacy action
- User must be able to enter identifying information (as specified in the identity string input)
- User must be able to submit this request

**Comment by adriaaaa** [comment]
completed and merged
