### ISSUE TITLE
[SaaS Connector] Sendgrid - initial support ("Contacts" endpoint)

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fidesops#252]
Create an integration with Sendgrid so we can process privacy requests.

See [requirements](https://ethyca.atlassian.net/wiki/spaces/OSS/pages/2211709198/Sendgrid+Connector+Specification)

**Comment by adamsachs** [comment]
https://github.com/ethyca/fidesops/commit/1c1fb896dc7d4475484a098db40a322dea470c51 adds some initial support for sendgrid integration: it's limited to only access requests, and only pulls down `contact` information, not `lists`

still need to look at erasure support, as well as traversing to `lists`. the latter likely requires updates to core saas connector framework, as there's a multi-value relationship between contacts --> lists.

**Comment by adamsachs** [comment]
closing this out, as the "Contacts" endpoint support is in place on https://github.com/ethyca/fidesops/pull/456

that PR will stay open until "Lists" endpoint support is implemented, which is covered in https://github.com/ethyca/fidesops/issues/455
