### ISSUE TITLE
Legacy Adaptor Recon

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fidesops#294]
Start with Salesforce.

if there is time in the sprint scan legacy adaptors to help identify features/requirements required to support SaaS Connectors

**Comment by galvana** [comment]
@adriaaaa, @Kelsey-Ethyca here is the list of framework enhancements based on this research

**Complete**
- OAuth2 Authentication (https://github.com/ethyca/fidesops/pull/555)
- Filter post-processor improvements (https://github.com/ethyca/fidesops/pull/584)

**Ticketed**
- Many to many relationships for collection dependencies (https://github.com/ethyca/fidesops/issues/458)
- API Key Authentication (https://github.com/ethyca/fidesops/issues/334)
- Custom Python overrides (https://github.com/ethyca/fidesops/pull/311)

**Ticket Needed**
- Response validators (status and body)
- Retry handlers
- Connector param default values

We can pick these up as needed based on the connector priorities.
