### ISSUE TITLE
Dev flow does not work with Windows

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fidesops#336]
### Bug Description

I tried contributing but parts of the Makefile/custom scripts didn't work. This seemed to mostly be related to me being on Windows.

#### Steps to Reproduce

1. run `make pytest-integration`

### Expected behavior

All Makefile commands should run regardless of OS

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS: Windows
* Python Version:
* Docker Version:

### Additional context

N/A

Aha! Link: https://ethyca.aha.io/features/OPS-91

**Comment by sanders41** [comment]
@ThomasLaPiana I saw you mention an error with the `@virtualenv` command in the integration test.

```sh
@virtualenv -p python3 fidesops_test_dispatch;
```

Could the problem be the `python3`? If I remember correctly `pythonn3` doesn't work on Windows and it should be `python` or `py`? I don't have a Windows computer so I can't test this and could be wrong.

**Comment by ThomasLaPiana** [comment]
it's definitely possible, but I need to dig in and identify the various places where issues are popping up

**Comment by ThomasLaPiana** [comment]
closed by #919
