### ISSUE TITLE
[User Management] Create New User

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fidesops#357]
### Is your feature request related to a specific problem?

1. Demonstrate that a Fidesops UI user can create a new user
1.1 Required fields are: username, First and Last name, password (this will be a temporary password that the new user will be forced to reset when they first log in to the UI), and at least one privilege
2. Given that the new user has received their correct credentials, when the user logs in for the first time, then they should be forced to set up a new password for their account
3. Ensure that the event of creating a new user was logged somewhere (we may need to discuss where with the rest of the team)

**Comment by LKCSmith** [comment]
Clarifying questions:
1. What is the BE endpoint to create a user?
2. How are we forcing the user to change password on log-in?
3. Is the part of logging-in for the first time as a new user a separate feature related to logins? What sort of indicator do they have that they need to change their password? How is this piece connected to the BE to validate it is the correct person logging in as this user and changing those credentials/posting them to the BE?

**Comment by adriaaaa** [comment]
> 1. How is the piece for a user to change their password on their first login connected to the BE to validate it is the correct person logging in, that it is their first time logging in, and that this is the correct user changing those credentials/posting them to the BE? Are their flags on the backend to validate the above + make sure it is their first time logging in themselves?

This would all need to be built. 

> 2\. Can a non-management user view their own profile? Can they make changes in a similar way once logged-in to their own information? Is it limited what they can edit (for example, could a user who didn't provision themselves edit their own privileges?)

Every user should be able to view their own profile from the little person icon in the upper right hand side of the screen. They should be able to edit their name and reset their password from that page, but should not be able to edit their privileges from that page.

If a user has the "user management" privileges, they should be able to see that menu option in the UI and select it to go to the user search page. They should be able to edit all users from that area of the app, including their own user.

If a user does not have "user mangement" privileges, they should not be able to see that "User Management" menu item.

I think the above answers #3 as well?
