### ISSUE TITLE
[User Management] Edit User

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fidesops#359]
### Is your feature request related to a specific problem?

1. Demonstrate that a UI user (with the correct Manage User Privs) can edit a users info
1.1 Editable fields are: First and Last name, selected privileges. (username should not be editable)

**Comment by LKCSmith** [comment]
Clarifying questions:
1. How is this view accessed? I see both "Edit" button and "Change Password" button on the page. 
2. Is this a different view from the profile landing page, or are we just hiding/showing buttons and/or modals on button clicks?
3. Does a POST/PATCH endpoint exist for users and what does it look like

Elements:
1. Editable fields
2. Buttons to edit/save/cancel
3. Change password modal (I think you mentioned only this field pops up a modal?)
4. Selected privileges checkboxes
