### ISSUE TITLE
Saas Tests Can't Run, But Appear Green

### ISSUE THREAD

**Issue by pattisdr** [ethyca/fidesops#371]
### Bug Description

https://github.com/ethyca/fidesops/runs/5861389373?check_suite_focus=true

Some incorrect formatting in the makefile is preventing the saas connector tests from running.  CI appears green however.

The specific error can be fixed here https://github.com/ethyca/fidesops/pull/370/files# (just a backslash missing), but the bigger issue is making sure that github actions is alerting us when tests can't run instead of swallowing that error.

```
Options:
    -d, --detach          Detached mode: Run container in the background, print
                          new container name.
    --name NAME           Assign a name to the container
    --entrypoint CMD      Override the entrypoint of the image.
    -e KEY=VAL            Set an environment variable (can be used multiple times)
    -l, --label KEY=VAL   Add or override a label (can be used multiple times)
    -u, --user=""         Run as specified *** or uid
    --no-deps             Don't start linked services.
    --rm                  Remove container after run. Ignored in detached mode.
    -p, --publish=[]      Publish a container's port(s) to the host
    --service-ports       Run command with the service's ports enabled and mapped
                          to the host.
    --use-aliases         Use the service's network aliases in the network(s) the
                          container connects to.
    -v, --volume=[]       Bind mount a volume (default [])
    -T                    Disable pseudo-tty allocation. By default `docker-compose run`
                          allocates a TTY.
    -w, --workdir=""      Working directory inside the container
e STRIPE_HOST -e STRIPE_API_KEY -e STRIPE_PAYMENT_TYPES -e STRIPE_ITEMS_PER_PAGE -e STRIPE_IDENTITY_EMAIL \
	fidesops pytest  -m "integration_saas"
/bin/sh: 1: e: not found
make: [Makefile:128: pytest-saas] Error 127 (ignored)
```

Similar type failure to https://github.com/ethyca/fidesops/pull/208

Aha! Link: https://ethyca.aha.io/features/OPS-88

**Comment by ThomasLaPiana** [comment]
@pattisdr is this still a problem?

**Comment by pattisdr** [comment]
These particular tests aren't failing anymore but this issue was around the fact that the tests were not running but CI was green.  Some kind of unit test that checked that the makefile had proper formatting might help with this.

**Comment by ThomasLaPiana** [comment]
given #919 , maybe that inherently solves it? it won't parse if it isn't correct Python, but that still wouldn't save us from a bug

**Comment by pattisdr** [comment]
sure, we can probably close this then
