### ISSUE TITLE
[Misc DevOps] `make mypy` is failing on M1 Macs

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#392]
### Bug Description

`make mypy` is failing on M1 Macs:

```
adam@Adams-MacBook-Pro fidesops % mypy .
mypy.ini:7: error: Error importing plugin "pydantic.mypy": cannot import name 'TypeVarDef' from 'mypy.types'
(/Users/adam/.pyenv/versions/3.9.11/envs/initial_dev3_9_11/lib/python3.9/site-packages/mypy/types.cpython-39-darwin.so)  [misc]
    plugins = pydantic.mypy, sqlmypy
    ^
Found 1 error in 1 file (errors prevented further checking)
```

#### Steps to Reproduce

1. Run `make mypy` on a Mac with an M1 chip

### Expected behavior

Mypy should run successfully and output something like:
```
root@de889783508e:/fidesops# mypy --ignore-missing-imports src/
Success: no issues found in 146 source files
```

See https://github.com/secretanalytics/secret-sdk-python/issues/7 for extra context

**Comment by sanders41** [comment]
Any chance these are related #367? Bumping the Pydantic version may help. It would also need to be bumped on the fides side to prevent a conflict with fidesctl.

**Comment by seanpreston** [comment]
I suspect they might be. Will cc @ThomasLaPiana here so he's aware.

**Comment by ThomasLaPiana** [comment]
we're on python 3.8, haven't seen this yet but I suspect that it's related to the python version. I think there were some typing changes made in 3.9 but I might be way off there

**Comment by sanders41** [comment]
@ThomasLaPiana you are correct. The issue seemed to start in 3.9
