### ISSUE TITLE
Add db execution support for composite primary key

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fidesops#42]
Currently, the execution definition only supports explicitly defined primary keys, however, there are certain datasets that only have composite primary keys, which the current implementation cannot support. This is a use case that is most frequently found in ETL tools and data warehouses. 

This feature is to:
* use combination of different fields to declare composite primary keys
* allow execution of requests using composite keys

**Comment by stevenbenjamin** [comment]
This functionality is supported, although there is not yet an explicit test for it.If you specify multiple fields with the "primary key" annotation, they should all be used for matching in updates. 

Note that the primary key annotation is _only_ used for update functionality, it is ignored in queries.

**Comment by pattisdr** [comment]
Fixed by #69 just wasn't linked - note that PK fields themselves can't be masked, this is a tricky problem, but one we'd be more likely to hit with composite primary keys.
