### ISSUE TITLE
Update masking API to support multiple input values per invocation

### ISSUE THREAD

**Issue by adamsachs** [ethyca/fidesops#441]
### Is your feature request related to a specific problem?
The masking engine project requires some updates to the core fidesops masking API. Specifically, per the [requirements doc](https://ethyca.atlassian.net/wiki/spaces/OSS/pages/2267873292/Fidesops-Plus+Masking+Engine+Requirements), the masking API should be updated to be able to take multiple input values (i.e., an array of values) to be masked. The masked values should also be returned as an array.

### Describe the solution you'd like
* The `/api/v1/masking/mask` endpoint should be updated such that its `value` query parameter support multiple values to be masked.
    * Fast API provides built-in support for multi-value query params, documented [here](https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#query-parameter-list-multiple-values). The client provides multiple values by simply repeating the query param, e.g. `/api/v1/masking/mask?value=value1&value=value2`.
     * Single value inputs to be masked should obviously still be accepted.
* The internal `MaskingStrategy.mask` abstract method should be updated accordingly to support a `List[str]` input as its `value` argument, and it should return a `List[str]`. Currently both are typed as just single-value `str`.
    * Importantly, this means that it is up to the particular `MaskingStrategy` implementation to define any sort of parallelization of work across the multiple input values. See alternatives considered below for more information.
* The response body to our masking call should be updated to pass back arrays of `plain` and `masked_value` values, rather than single-value fields.
    * This should be considered a breaking public API change, in that we are changing the public-facing API here. We are not aware of anyone using this the `/mask` API directly at this point, so it should have minimal public-facing impact.
* The internal use of the masking functionality by other `fidesops` operations will need to be updated, since the `MaskingStrategy.mask` abstract method's signature will be changed. These changes should be minimal - passing in singleton lists and handling singleton lists that are returned.
* The existing `MaskingStrategy` subclasses will need to be updated to support the `mask` method updates. At this point, all existing `MaskingStrategy` subclasses should just simply loop through their input values serially. This should mimic existing functionality.
    * As a note, the NLP `MaskingStrategy` implementation, which this ticket is aimed at supporting eventually, but has not yet been implemented in fidesops, should implement more complex handling of multi-value input. That work is not in scope for this specific ticket.

### Describe alternatives you've considered, if any

I've considered whether we should avoid changes to the internal API (i.e. the `MaskingStrategy.mask` abstract method), keeping that as a single-value operation, and instead only update the thin public API layer to take multiple input values. The solution described above pushes multi-value support further down the stack, which I think increases flexibility in how individual masking strategies handle multi-value inputs. Rather than imposing any strategy on the "abstract" level, we give each masking strategy the leeway to implement any parallelization or special-handling of multiple input values how it wishes. Looking specifically toward the thrust of this ticket -- the NLP masking support -- this means we can implement a handling multiple free-text input values to mask in a way that is optimized for the specific NLP masking processing, without having to worry about whether this handling is generally optimal for other types of masking strategies.

Given that our API calls still only support one masking strategy per call (i.e., multiple values but not multiple masking strategies), this implementation also doesn't limit us in any way. If, at some point, there were compelling reasons to support multiple values and multiple masking strategies per API call, we may look to revisit the implementation here and support parallelization at the abstract level, i.e. across the different masking strategies provided.

**Comment by NevilleS** [comment]
Yup, these requirements look good to me!

My comment is an implementation detail on the API design: I'm not sure how developer-friendly it is to pass multiple values as query params. Say, for example, you have 3 strings like:
```python
data = ["My name is Neville Samuell", "I live in New York City", "I like margherita pizza"]
```

If you pass those as query params to the API, you end up URL encoding them right:
```
PUT /api/v1/masking/mask?value=My%20name%20is%20Neville%20Samuell&value=I%live%20in%20New%20York...
```

That "feels" kind of messy to me, and my instinct would probably be to just put the data in the request body instead. I think it's also less likely to "leak" personal data in the URLs, too, since URLs often get persisted to logs?

**Comment by NevilleS** [comment]
Admittedly, the current API takes `value` as a query param, but we can make that change too if we like. I'd recommend getting an opinion or two from the team and then shipping it 👍

**Comment by adamsachs** [comment]
just noting here that another compelling reason to switch the `value` to a request body field rather than a query param, related to what @NevilleS noted above, is URL length limits: we are anticipating potentially large blocks of text being passed as inputs to the masking API, and we could therefore easily have use cases go above the [de facto ~2k URL character limit](https://stackoverflow.com/a/417184), if those input values were encoded as a URL query param
