### ISSUE TITLE
Allow a `PrivacyRequest` level encryption key to be supplied on request creation

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#46]
Fidesops must support the ability to supply a custom encryption key on request creation, that will be used throughout the PrivacyRequest flow. This encryption key should be used to encrypt the access data we return to the user at the end of a request before it is uploaded in either JSON or CSV format.

This encryption key can be ignored for erasure policies for now.

**Comment by pattisdr** [comment]
Pieces we still need to settle on:

- How will the encryption key be specified in the request? Old planning docs suggest it should be sent as a request header using a custom ethyca header parameter, but this might be outdated.
-  How do we temporarily store the encryption key? it could be cached in Redis alongside the identities or stored encrypted itself on the PrivacyRequest, I like the latter.
- What encryption algorithm do we want to use here? We already have support for AES GCM Encryption, but there's this bit about the nonce, if we are generating it ourselves (in which case, we need to give this to the user somehow), or they are supplying that too.

**Comment by pattisdr** [comment]
Updates:

- How we will specify encryption key: Via a request header with the custom parameter `x-fidesops-encryption-key`
- Encryption key will be temporarily cached like identities
- We will use AES GCM to encrypt, requiring use to supply both nonce and encryption key.
