### ISSUE TITLE
Create image for Fidesops OAuth2 reverse-proxy server

### ISSUE THREAD

**Issue by galvana** [ethyca/fidesops#489]
### Is your feature request related to a specific problem?
Create the Docker image for a Fidesops reverse-proxy server.

### Describe the solution you'd like
- Use `nginx` as the base image
- Include a `nginx.conf` to define the forwarding rules for Fidesops' `/api/v1/oauth/callback` endpoint
- Host auth server on https://fidesplus.ethyca.com (or something else if we have an established naming convention)
  - https://ethyca.atlassian.net/wiki/spaces/EN/pages/2279538853/SaaS+Connector+OAuth2+Authentication?focusedCommentId=2285961373#comment-2285961373
- Should be still be able to use our ngrok account by passing the tunnel name as the oauth2 state
  - determine the labels to use for ngrok (refer to legacy nginx.conf)

### Additional context

- https://ethyca.atlassian.net/wiki/spaces/OSS/pages/2279538853/SaaS+Connector+OAuth2+Authentication
- Internal use only for now

### Questions
- Where should the Docker file and nginx.conf be hosted (Github, Gitlab)?
  - Should this be open source? 

Aha! Link: https://ethyca.aha.io/features/OPS-61

**Comment by nschoenbrot** [comment]
https://ethyca.slack.com/archives/C03BB3HEDQR/p1656442661457499

**Comment by galvana** [comment]
This was converted to an internal ticket and this work is no longer needed.
