### ISSUE TITLE
Fidesops Privacy Center throws error in a production build: "Type error: Property 'name' does not exist on type '{ email: string; }'."

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fidesops#492]
### Bug Description

When running `next build` to generate production assets for the privacy center, the build fails like so:
```
./components/RequestModal.tsx:133:50
Type error: Property 'name' does not exist on type '{ email: string; }'.

  131 |       }
  132 | 
> 133 |       if (!values.name && action.identity_inputs.name === 'required') {
      |                                                  ^
  134 |         errors.name = 'Required';
  135 |       }
  136 
```

#### Steps to Reproduce

1. `cd clients/privacy-center`
2. `npm install`
3. `npm run build` or `npx next build`

### Expected behavior

This should create a production build that can then be run via `npm run start`

### Environment

* Version: 1.4.1
* OS: macOS Monterey 12.3.1 (21E258)

**Comment by eastandwestwind** [comment]
I received a different error on latest `main`: 

```
./pages/index.tsx
31:5  Error: Arrow function expected a return value.  consistent-return
```

After resolving locally, I did not run into the original type error described in this ticket.

I'll push out my local fix here.
