### ISSUE TITLE
Adobe Experience (Campaign Standard) Connector

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fidesops#516]
Specs [here](https://ethyca.atlassian.net/wiki/spaces/OSS/pages/2305261585/Adobe+Experience+Campaign+Standard+Connector+Specification)

### Additional Information
exclude custom resource endpoint in this ticket. Will be handled in https://github.com/ethyca/fidesops/issues/859

Aha! Link: https://ethyca.aha.io/features/OPS-53

**Comment by nschoenbrot** [comment]
https://ethyca.slack.com/archives/C03BB3HEDQR/p1656360849726939
