### ISSUE TITLE
Ability to revoke/cancel a request

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fidesops#525]
### Description
A privacy request manager may need to cancel a request in case it was submitted in error or approved in error. Furthermore, as part of Consumer Report's DRP specification, they do require support for revoking a request in the event that the consumer chooses to do so.

This may be challenging to do for in progress requests at this time. We have limited the scope of this ticket to support cancelling a request only if the request is in a NEW state.

### Acceptance Criteria
1. Demonstrate that a request can be cancelled (limit to only requests that haven't started processing aka NEW requests)
2. If a request was cancelled, demonstrate that the status of the request moves to "Cancelled"
- on the SR landing/list page, we should update the status dropdown to include "cancelled" as a filterable status
- you should not be able to restart cancelled requests (users should submit new requests)

Aha! Link: https://ethyca.aha.io/features/OPS-51

**Comment by pattisdr** [comment]
https://github.com/ethyca/fidesops/issues/418
