### ISSUE TITLE
[Spike] How can we pass params into `fideslib` dependency injection?

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#561]
The best example of this is how can we pass the logic to fetch the sqlalchemy DB session (the result of `get_db()`) into the API routes that require it? Do we actually need to pass the `get_db` method itself in?

- `fideslib` provides a config but doesn't access it itself.
- Can we use `functools.partial` <— this lets us pass the name of a function and params.
- Otherwise, can we include the `get_db` logic inside `fideslib`?

**Comment by ThomasLaPiana** [comment]
potentially a silly question, but why do we have to use dependency injection at all? Other than a bit of syntactic sugar/guardrails why not pass the connection session itself?

This is what we do in `fidesctl`, API endpoints have no idea that the database exists.

**Comment by sanders41** [comment]
@ThomasLaPiana this is one option @seanpreston and I discussed. The other option that looks promising right now is for `get_db` to be in `fideslib` and everyone can use it from there.

**Comment by NevilleS** [comment]
Question from me: how will we end up "loading up" all the models & endpoints? I assume we'll end up importing an `APIRouter` at some point, so maybe we can subclass that and inject those dependencies like so:
```
from fideslib import FideslibRouter

fideslib_router = FideslibRouter(prefix=V1_URL_PREFIX, get_db_fn=get_db, ...)
```
(see https://github.com/ethyca/fidesops-plus/pull/6/files#diff-585a2e9d897ffbd47df61ed9efb432c1c7193e4d88cb147cd5e84e5b4ca3a9faR8 for an example)

**Comment by seanpreston** [comment]
That's a great suggestion @sanders41
