### ISSUE TITLE
Update clipboard icon to latest version

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fidesops#599]
### Is your feature request related to a specific problem?
The design team has released the latest version of the copy/clipboard icon. We will need to update all pages that use it.

Media icons can be found in the "Fides UI library" in Figma.

Aha! Link: https://ethyca.aha.io/features/OPS-39

**Comment by seanpreston** [comment]
We'll save this for Chris Calhoun's first day

**Comment by eastandwestwind** [comment]
@adriaaaa I'm not seeing the copy/clipboard icon in figma. Mind showing me specifically where it is?

**Comment by adriaaaa** [comment]
@conceptualshark this is the ticket where we are updating the clipboard icon. Not a high priority but in case you have any images in the docs using this icon, then we should update our docs.

**Comment by adriaaaa** [comment]
> @adriaaaa I'm not seeing the copy/clipboard icon in figma. Mind showing me specifically where it is?

@eastandwestwind did my slack tag help answer this question?

**Comment by eastandwestwind** [comment]
@adriaaaa yup I got it, thanks!
