### ISSUE TITLE
Accept an arbitrary path to `/migrations` in config

### ISSUE THREAD

**Issue by PSalant726** [ethyca/fidesops#612]
### Bug Description

PyPI installs the fidesops `/migrations` directory outside of the package source tree, in a sibling directory of `/fidesops`. Currently there is no way to specify a path to DB migrations that exists outside of the `/fidesops` package source tree.

#### Steps to Reproduce

1. `pip install fidesops`
1. `docker run -it --rm fidesops_fidesops bash`
1. Inside the container, observe:
    ```
    $ tree -L 2 /usr/local/lib/python3.9/site-packages/
    site-packages/
    ├─ fidesops/
    │  ├─ __init__.py
    │  ├─ ...
    ├─ migrations/
    │  ├─ versions/
    │  ├─ __init__.py
    │  ├─ ...
    ├─ ...
    ```

### Expected behavior

Fidesops may accept an arbitrary file path to the `/migrations` directory via ENV variable configuration.

### Additional context

This is required for fidesops-plus to start successfully.

**Comment by PSalant726** [comment]
Thinking more about the changes on #613, it might be better to simply move the `/migrations` directory inside of `/fidesops` instead. Thoughts @seanpreston @sanders41 ?

**Comment by sanders41** [comment]
I haven't seen migrations inside the package directory before, but this is a unique case. I think the idea of putting it in `/fidesops` makes sense here. `pip install fidesops` resulting in `migrations` being installed as it's own module in the virtual environment makes it unclear why the module is there, or where to find it when wanting to use it.

**Comment by PSalant726** [comment]
@sanders41 

> I haven't seen migrations inside the package directory before

It turns out that it's done this way in fidesctl. That's where I got the idea.

> `pip install fidesops` resulting in `migrations` being installed as it's own module in the virtual environment makes it unclear why the module is there, or where to find it when wanting to use it.

I completely agree. Closing this issue and #613 in favor of #615.

**Comment by EricErney** [comment]
Trying to fix
