### ISSUE TITLE
Publish fidesops to pypi

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fidesops#62]
We should be able to offer `pip install`, so please let's publish to pypi

**Comment by NevilleS** [comment]
I don't think we should do this, given the rather complex system requirements for fidesops (various drivers, etc.), I don't think the `pip` ecosystem is a great fit for this...

We can continue to distribute `fidesops` via Docker Hub. Is there a specific need for a `pip install` equivalent?

**Comment by NevilleS** [comment]
In fact, I think this issue was created based on a requirement I originally wrote, so I'll close this for now unless someone wants to reopen
