### ISSUE TITLE
MyPy settings causing errors to be ignored

### ISSUE THREAD

**Issue by sanders41** [ethyca/fidesops#629]
With the current settings of mypy it is set to globally ignore missing imports. One problem with this is, because of the project structure, mypy is seeing imports from fidesops itself as missing imports. With this, many of the checks mypy is supposed to be doing it is instead ignoring. Adding a `py.typed` file to the `src/fidesops` directory fixes the missing import issue for fidesops modules, but also produces a long list of mypy errors that need to be addressed.

Completion of this ticket should also include https://github.com/ethyca/fidesops/issues/631

Aha! Link: https://ethyca.aha.io/features/OPS-32

**Comment by adriaaaa** [comment]
@conceptualshark I am not sure if we need to update our docs anywhere with this page.
