### ISSUE TITLE
[Spike] Serve Admin UI from `/` instead of `/static/index.html`

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#666]
Timebox - 1 day
Right now when you serve admin UI it serves on something that isn't ideal. It's not conventional to access UIs from a static directory.
Ideally we would serve it from the root and not a static html.

**Comment by adriaaaa** [comment]
Trailing slashes topic should be addressed in this PR

To be addressed in the future - updating how the routing is handled in the front end. Routes you see in url are not representative of what you see in the BE. Impact of current PR: when the URL is sent to the backend it will try to find a file that does not exist so we redirect to home page.

@TheAndrewJackson to write up a design doc on the next steps to be considered in the future.
