### ISSUE TITLE
Policy-driven masking - handle new data_type and length params

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fidesops#70]
The ability to mask data during the query execution needs to be driven by the specified policy. This ticket will add support for the following strategies, specifically implementing the framework to handle new `data_type` and `length` params (#100 will add support for remaining strategies):

- [   ] HMAC
- [   ] Hash
- [   ] AES Encryption
- [ x ] Null
- [ x ] Random string rewrite
- [ x ] Default string rewrite

With configuration support for format-preservation for all above strategies 

This will ensure that, during a deletion privacy request execution, we will be able to:
* mask values in the connected database by data category 
* mask data per the policy's specified masking type 
(edited)

**Comment by NevilleS** [comment]
Can we change that list to the current supported options:
* Null
* String Rewrite
* Hash
* Random String Rewrite
* AES Encryption
* HMAC

Also note that "format-preservation" was a configuration option added to several of those strategies... I don't remember exactly which ones but I think all of them. Our documentation is light on this right now and we should also add a related issue to update the docs with the configuration options for each of the above 👍

**Comment by pattisdr** [comment]
Just to link to the work that's already been done, recently merged https://github.com/ethyca/fidesops/pull/31 introduced pulling the masking strategy off of the policy and masks values by data category, however, as a first step, it restricted to only allowing the null masking strategy to be set in the first place.
