### ISSUE TITLE
Send X-Fides-Source Header in privacy-center datastore-connection.slice.ts

### ISSUE THREAD

**Issue by eastandwestwind** [ethyca/fidesops#711]
This was missed in datastore connection UI. It will allow our analytics service to properly identify all endpoint calls from our UI.

**Comment by TheAndrewJackson** [comment]
@eastandwestwind I think I did this in a recent PR. Does this look correct to you? [link](https://github.com/ethyca/fidesops/blob/main/clients/admin-ui/src/features/datastore-connections/datastore-connection.slice.ts#L143-L147) 

I also refactored the `prepareHeaders` calls slightly to make the Typescript type checker happier. It made it so the `any` type isn't needed anymore for the `datastoreConnectionApi` variables. I guess it couldn't resolve the type when returning a function.

**Comment by eastandwestwind** [comment]
@TheAndrewJackson yayy this looks great. Thanks so much. I'll close out this ticket.
