### ISSUE TITLE
Salesforce (erasure)

### ISSUE THREAD

**Issue by galvana** [ethyca/fidesops#713]
### Description

Add erasure functionality for the following collections. Salesforce allows `PATCH` actions for these endpoints so we should be able to mask individual fields.

|Collection|Request|
|---|---|
|contacts|`PATCH` /services/data/v54.0/sobjects/Contact/<contact_id>|
|cases|`PATCH` /services/data/v54.0/sobjects/Case/<case_id>|
|leads|`PATCH` /services/data/v54.0/sobjects/Lead/<lead_id>|
|accounts|`PATCH` /services/data/v54.0/sobjects/Account/<account_id>|
|campaign_members|`PATCH` /services/data/v54.0/sobjects/CampaignMember/<campaign_member_id>|

**Comment by nschoenbrot** [comment]
Left a question here: https://ethyca.atlassian.net/wiki/spaces/EN/pages/2263777340/Salesforce+Connector+Specification?focusedCommentId=2364014609
