### ISSUE TITLE
[Datastore Management] Double line border between 2 neighboring datastores

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fidesops#746]
### Bug Description

When there are datastore cards next to each other, there is a double outline instead of a single outline. This isn't blocking, but would be fine in a follow-up, even in next release imo.

#### Steps to Reproduce

1. Have at least 2 datastores configured
2. go to datastore management landing page
3. view borders between "cards"

### Expected behavior

View mocks in [Figma](https://www.figma.com/file/MTbZohIGvB4bq2f2wkiDHO/Fidesops-Management-UI?node-id=994%3A11697)

### Screenshots

![image](https://user-images.githubusercontent.com/87208929/176196168-77df9a04-efb6-410b-a0f4-5e88e93e4332.png)

### Environment

* Version: Fidesops 1.6.0

**Comment by chriscalhoun1974** [comment]
@adriaaaa Yes, you can close this bug. Bug has been resolved.

<img width="1131" alt="Screen Shot 2022-07-21 at 1 07 59 PM" src="https://user-images.githubusercontent.com/68459950/180272947-a90a96f8-91fe-4144-9047-a940aa2c42e8.png">
