### ISSUE TITLE
Users should be able to click on the full field of a dropdown-type filter to open up the dropdown

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fidesops#747]
### Is your feature request related to a specific problem?

This can be seen on the datastore management landing page where only the small arrow element is clickable on the dropdown. 
![image](https://user-images.githubusercontent.com/87208929/176197234-54e81ed4-fa64-4a32-82dd-665689614222.png)

### Describe the solution you'd like

The entire filter should be clickable to open up/close the dropdown. We should make sure all filters like this across the UI behave like this.

Update existing dropdown filter to dropdown component

**Comment by chriscalhoun1974** [comment]
![Image](https://user-images.githubusercontent.com/68459950/179884692-7599c5bd-e079-4122-b537-227809489f60.png)
