### ISSUE TITLE
Update to Fideslang 1.1.0

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fidesops#757]
See the Fideslang 1.1.0 milestone.

**Comment by ThomasLaPiana** [comment]
@SteveDMurphy I'm happy to hop in and help here as this is also related to the repo merger

**Comment by SteveDMurphy** [comment]
> @SteveDMurphy I'm happy to hop in and help here as this is also related to the repo merger

Cool cool, thanks @ThomasLaPiana - I was planning on starting on this first thing next sprint but we can at least get started on it since it sounds like it is potentially blocking a couple of things 👍🏽
