### ISSUE TITLE
Add a Connection - Select a connector to configure (front end)

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fidesops#760]
### Use Cases

As the owner of a system that contains PII, I need the ability to select a connector to configure so that I can specify the connection details so Fides can query that system to fulfill a privacy request.

### Assumptions
* The scope of this ticket is limited to selecting a SaaS type connector
* We do not have the concepts of "categories" yet, so exclude this from the "Choose your Connection" screen for now.
* use feature flag for this body of work
* dual sorting will be handled on the FE
* reminder - do not include the categories menu on left

### Acceptance Criteria
1. Demonstrate that a user can add a new connection
* If there are no connection configured, show that "no connections" landing page (note: this page may already exist, will need to confirm if it does or not. also confirm that it matches the above mockup)
* If there already connections configured, the button for "Create a Connection" should appear above the list of configured connections.
* When use selects "Add a New Connection" they should be taken to a page where they can choose from a list of supported connectors.
* The list of supported connections should be displayed in ascending alphanumeric order. 
* No pagination, just display an entire list of supported connectors
2. Demonstrate that a user can narrow down the list of available connectors
* This will be done via dropdown with options for  "Third party connectors" and "Database connectors"
* The dropdown for type of connector should default to showing all connector types.
* "Database connectors" should be greyed out/read-only. When user hovers over the "Database connectors" option they should see a tooltip that says "You cannot add database connections from here at this time. Please refer to our [documentation](https://ethyca.github.io/fidesops/guides/database_connectors/) on how you can do so from our API."(note this is temporary until we can support adding database connectors)
3. Demonstrate that a user can search for a specific connector.
* search by the name of the type of connector (e.g. "Slack" or "Hubspot")
* When searching for a connection, use the "TypeAhead" we discussed.
4. Show that a user can go back to the landing page by selecting the breadcrumb under the title OR selecting the "Datastore Connections" menu option.

### Mockups
[Figma](https://www.figma.com/file/MTbZohIGvB4bq2f2wkiDHO/Fidesops-Management-UI?node-id=106%3A1469)
![Image](https://user-images.githubusercontent.com/87208929/179291403-451c7bde-b3cc-4dbc-8097-adf72cc86029.png)

![Image](https://user-images.githubusercontent.com/87208929/179293845-b5a82d4a-8038-4f87-8dc9-4d48d1308be3.png)

![Image](https://user-images.githubusercontent.com/87208929/179291864-025df51f-a8e8-4cf2-8ee7-dca6c99f4f59.png)

### Additional Dev Notes
For SaaS connection configs, we need to modify the fides_key in the example SaaS configs/datasets before inserting into the database. We already have a ticket outlining this, and other related work in https://github.com/ethyca/fidesops/issues/814. Please keep #814 in mind for when working on #760 and reach out to @galvana if there are any questions.

**Comment by chriscalhoun1974** [comment]
@adriaaaa To expand Dawn's question above, should the list of connection types be grouped by Sass and Database? What I'm suggesting is adding a header label above each list (Sass/Database) within the grid results.

**Comment by pattisdr** [comment]
Backend support ticketed here: https://github.com/ethyca/fidesops/issues/910
