### ISSUE TITLE
[DB Compatibility] Query execution for scalar values in MariaDB

### ISSUE THREAD

**Issue by iamkelllly** [ethyca/fidesops#79]
Requires #75  to be complete first.

We need to enable the MariaDB database connector to be able to read/write to the database itself during query execution.

**Comment by eastandwestwind** [comment]
As part of this ticket, ensure that the fixtures are split into fixture functions: 

context- https://github.com/ethyca/fidesops/pull/186/files#r795994350

"One step better from here (and what I'm aiming for in the other PR) is to split these into fixtures functions themselves, such that you could have mariadb_customer as a fixture, and that generates a brand new customer row in the DB (and any such dependencies) off Faker generated data — that's a stretch goal here"
