### ISSUE TITLE
[Spike] IAM authentication for S3 storage configs

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#822]
Some users would like to authenticate their S3 `StorageConfig`s via IAM instead of client id and secret.

Details:
* Large organizations have a security officer that reviews an orgs infrastructure
* if you want to get new infrastructure, you. have to review it by the security team
* MMTV has a policy for s3 buckets - it doesn't allow API key or secret to be used. They require users to be configured under an IAM policy that is more secure than using a token.
* cant be in a dev environment because we need to connect their datastores but we can't move to their staging S3 without IAM policies

This issue duplicates [#695](https://github.com/ethyca/fidesops/issues/695).

**Comment by seanpreston** [comment]
This is blocked until @daveqnet has created a dev account for @TheAndrewJackson

**Comment by daveqnet** [comment]
> This is blocked until @daveqnet has created a dev account for @TheAndrewJackson

AWS sandbox account created for and credentials shared with @TheAndrewJackson. This is now unblocked.

**Comment by TheAndrewJackson** [comment]
@seanpreston Do you have any more info on this requirement? I'm not sure I understand exactly what it means in this context.

> MMTV has a policy for s3 buckets - it doesn't allow API key or secret to be used. They require users to be configured under an IAM policy that is more secure than using a token.

I'm new to AWS so I might be missing something. In my research it looks like requests to AWS requires `aws_access_key_id`, `aws_secret_access_key`, and `aws_session_token`. It's possible to get a set of temporary credentials by [assuming a role](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-api.html). Getting the temporary credentials still requires a set of `aws_access_key_id` and `aws_secret_access_key` keys to make the request to AWS.

They could potentially give fidesops a set of `aws_access_key_id` and `aws_secret_access_key` keys that don't have access to S3 and won't rotate. Then fidesops could assume the role that does have access and use the temporary credentials to upload to S3.

That doesn't seem to align exactly with what the bullet point is saying though.

**Comment by seanpreston** [comment]
In this flow, the EC2 instance is given the IAM role on creation, where the role includes the permissions policy that grants the specified access. For this increment we'll need Fidesops to access the role credentials from the instance, then apply those credentials when trying to interface with S3. Specifically in step 3:

> When the application runs, it obtains temporary security credentials from Amazon EC2 [instance metadata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html), as described in [Retrieving Security Credentials from Instance Metadata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials). These are [temporary security credentials](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html) that represent the role and are valid for a limited period of time.

> With some [AWS SDKs](http://aws.amazon.com/tools/), the developer can use a provider that manages the temporary security credentials transparently. (The documentation for individual AWS SDKs describes the features supported by that SDK for managing credentials.)

> Alternatively, the application can get the temporary credentials directly from the instance metadata of the Amazon EC2 instance. Credentials and related values are available from the iam/security-credentials/role-name category (in this case, iam/security-credentials/Get-pics) of the metadata. If the application gets the credentials from the instance metadata, it can cache the credentials.

so it'd be good to check if there's a library that supports this. We'd also need to build in some app-level check that the deployment is on EC2, as the method may vary depending on deployment type.

Source: [Using an IAM role to grant permissions to applications running on Amazon EC2 instances](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html)

**Comment by TheAndrewJackson** [comment]
@seanpreston Thanks, that was very helpful. It looks like it's relatively straightforward to get the current role of a given EC2 instance. 

In order to get the temporary credentials a request is made to `http://169.254.169.254/latest/meta-data/iam/security-credentials/<ROLE>` with `ROLE` being the desired role that the EC2 instance will assume. If the EC2 instance has access to the role AWS will return a response that looks like this
```json
{
  "Code" : "Success",
  "LastUpdated" : "2012-04-26T16:39:16Z",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : "ASIAIOSFODNN7EXAMPLE",
  "SecretAccessKey" : "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
  "Token" : "token",
  "Expiration" : "2017-05-17T15:09:54Z"
}
```

There is an open source library that handles retrieving and caching [EC2 metadata](https://github.com/adamchainz/ec2-metadata). So this work may already be done for us.


Fidesops could add an optional `aws_ec2_instance_role` key to the `StorageSecretsS3` schema. When the subject request goes to upload the result to S3 it would check if `aws_ec2_instance_role` was set and request the temporary credentials. Otherwise it would fallback to how it's currently done.


Source: [https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials)

**Comment by iokamoto-sm** [comment]
I guess you are already clear about what to do. Just in case. Boto3 handles the credentials as described at:

https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials

My understanding is fidesops is doing either of the following.

* Passing credentials as parameters in the boto.client() method
* Passing credentials as parameters when creating a Session object

Our ask is to support [Assume Role provider](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#assume-role-provider), which Boto3 takes care of it automatically.

**Comment by TheAndrewJackson** [comment]
Thanks @iokamoto-sm. That's correct. Currently fideops is passing in the credentials manually to create a session. It looks like the "Assume Role provider" docs say that authenticating with that method requires that the `/.aws/credentials/` and `/.aws/config` files be configured. Is that how you're expecting to authenticate with AWS?

**Comment by iokamoto-sm** [comment]
Hi @TheAndrewJackson , It is not a config file but the equivalent env variables like the following. This is what we get when we deploy fidesops into EKS Fargate. Boto3 handles credentials automatically.

```bash
$ env | grep AWS
AWS_DEFAULT_REGION=us-west-2
AWS_REGION=us-west-2
AWS_ROLE_ARN=<arn for the role>
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_STS_REGIONAL_ENDPOINTS=regional

```
