### ISSUE TITLE
Backend for SaaS Connector Logos

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#828]
Right now we need an individual API call for a connection config to retrieve the SaaS connection type that's needed to display the logo for that connector. We'd like to optionally include the SaaS type in the response for all connection configs by:
- adding `saas_config` as an optional field to the returned schema for each connection
- adding a field within `saas_config` to indicate the type

**Comment by adriaaaa** [comment]
Good issue to consider to pull in if people are looking for work

**Comment by eastandwestwind** [comment]
GET `{{host}}/connection` will now return something like this:

```
{
    "items": [
  {
      "name": "Sentry Connection Config",
      "key": "sentry_saas_key",
      "description": null,
      "connection_type": "saas",
      "access": "write",
      "created_at": "2022-06-28T12:22:04.572150+00:00",
      "updated_at": "2022-06-28T18:45:16.543066+00:00",
      "disabled": true,
      "last_test_timestamp": null,
      "last_test_succeeded": null,
      "saas_config": {
          "fides_key": "sentry_connector",
          "name": "Sentry SaaS Config",
          "type": "sentry"
      }
  }
}}
```
