### ISSUE TITLE
[User Management] Create new user gives HTTP 422 Unprocessable Entity exception.

### ISSUE THREAD

**Issue by chriscalhoun1974** [ethyca/fidesops#832]
### Bug Description

When a FidesOps user is creating a new user and clicks the "Save" button, the following toast error message is displayed:

`utf-8' codec can't decode byte 0xd8 in position 4: invalid continuation byte`

Via Chrome DevTools, you can see the API endpoint (http://0.0.0.0:8080/api/v1/user) POST is invoked resulting in a HTTP 422 Unprocessable Entity exception.

#### Steps to Reproduce

1. Login into FidesOps
2. Click User Management tab
3. Click Add New User button
4. Fill out the form 
5. Click the Save button

### Expected behavior

What should happen is that the /api/v1/user endpoint should return a HTTP 200. User should be redirected back to the User Management landing page and visual see the new created user.

### Screenshots

![Screen Shot 2022-07-07 at 8 28 59 PM](https://user-images.githubusercontent.com/68459950/177896783-30e7b57b-a7e1-4140-a7e4-3d4bac753e9f.png)

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by sanders41** [comment]
Closed via #833
