### ISSUE TITLE
Retry a DSR (FE)

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fidesops#863]
### Is your feature request related to a specific problem?

Can reprocess from the BE, but need to provide ability to do so from FE

Acceptance Criteria
1. Demonstrate that a user can retry an ERRORED subject request from the UI
- retry should not be supported on other SR states (i.e. New, in progress, completed, etc)

**Comment by pattisdr** [comment]
Just a note to clarify backend functionality, we can currently resume a "paused" or a "failed" request from the paused/failed collection, but there's no support for reprocessing from an arbitrary point https://github.com/ethyca/fidesops/issues/523

**Comment by adriaaaa** [comment]
Ah right, thanks for the reminder @pattisdr . I've drafted up some reqs and will review with you soon.

**Comment by chriscalhoun1974** [comment]
@adriaaaa @pattisdr Should the Retry button be disabled after a certain # of failed attempts?

**Comment by chriscalhoun1974** [comment]
@adriaaaa @pattisdr When the user clicks the `Retry` button, I have added a spinner to the end of the button and changed the text to `Retrying`. If the API endpoint has returned a successful response, the Status badge will be updated to `In Progress` in which the `Retry` button will no longer be displayed. If the API endpoint returns an exception, a toast message is rendered. Please let me know if you have any objections or would like to discuss the expected user experience further. Thank you.

![Image](https://user-images.githubusercontent.com/68459950/180825627-261d0884-2689-4b77-b097-0c2824740936.png)

**Comment by adriaaaa** [comment]
That sounds great to me thanks @chriscalhoun1974
