### ISSUE TITLE
Reprocess a DSR when a collection was added to be referenced before already-completed collection

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fidesops#868]
### Is your feature request related to a specific problem?
See Scenario D on the diagram on this [page](https://ethyca.atlassian.net/wiki/spaces/PM/pages/2376302908/Reprocessing+a+Subject+Request)

In order to gain insight into error scenarios, we will be addressing https://github.com/ethyca/fidesops/issues/754 first.

**Comment by pattisdr** [comment]
Could be replaced with this design spike https://github.com/ethyca/fidesops/issues/1036, which would cover this scenario and other scenarios we're not handling
