### ISSUE TITLE
Update Fidesdemo to Fidesops 1.6.3

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fidesops#880]
### Is your feature request related to a specific problem?

We need to make sure that our demo is using the latest version of fidesops.

### Acceptance criteria
1. Show that the demo is pointing to the latest version of fidesops
- don't need to update the docker tag on this ticket
2. Confirm that the following are scenarios are successful:
- Connected datastores are visible in the datastore connections space
- A privacy request can be submitted and denied --> a denial reason should be inputted and then subsequently displayed on the SR detail page)
- An access request can be submitted and approved --> request should process through the connected datastores and a resulting data package should appear in the connected storage location.
- An erasure request can be submitted and approved --> request should process through the connected datastores and user should be able to confirm that the correct information was erased.
- New users can be created in the User management space
- Users can be deleted from the User management space
3. Please coordinate with Johnny to confirm that he can do perform his demo.

**Comment by seanpreston** [comment]
I've updated the title of this ticket to specify Fidesops 1.6.3, as 1.6.2 won't build correctly on Docker

**Comment by adriaaaa** [comment]
Consider making a change to CI to catch type errors in the future.
