### ISSUE TITLE
[Spike] Dataset APIs (Timebox: 3 days)

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesops#982]
## Overview

Future versions of our Connection creation and Dataset management feature require Fidesops to have more granular control over the contents of the Datasets that sit within it (see: below).

[https://user-images.githubusercontent.com/1667340/181581490-0abeaeff-8d39-49f2-9022-a1ee752c558c.png](https://user-images.githubusercontent.com/1667340/181581490-0abeaeff-8d39-49f2-9022-a1ee752c558c.png)

## Current functionality

Currently Fidesops can: - return full datasets as JSON - return all datasets as JSON - create a new dataset from YAML - update an existing dataset from YAML - create a new dataset from JSON - update an existing dataset from JSON

What's not supported is the ability for Fidesops to return Dataset features in a more granular way. For example: - create/read/update/delete a collection in a dataset - create/read/update/delete a field within a collection - create/read/update a field's references

## Option 1

Fidesops could technically keep the APIs unchanged, pushing the burden of granular updates to the client side. For example, a client could maintain a dictionary of the current state of a dataset, and read / write changes to / from that, before posting up the entire dataset to the server each time a change is made.

Pros: - less API changes for the backend to get ahead of

Cons: - complex state management in the client, which could reduce performance dramatically as the number of datasets in the Fidesops installation scales - the server will need to validate the entire dataset each time it's changed

## Option 2

Fidesops supports endpoints for granular control of Dataset collections, fields, and field metadata.

Pros: - much simpler from a client side perspective - validation can happen on a field / collection level, instead of requiring the entire dataset - note: this won't change the need to potentially validate entire datasets each time a field reference changes

## Questions

- Does Fidesctl already have this granularity in its APIs?
  - @ThomasLaPiana or @NevilleS are probably best placed to source an answer for this

**Comment by ThomasLaPiana** [comment]
no, currently we only have endpoints for top-level resources

Additionally as a side-note, fidesctl handles dataset collections and fields as json objects within a dataset object, not as separate tables with foreign_keys so this would be a significant bit of engineering to accomplish in fidesctl

**Comment by pattisdr** [comment]
Output of design doc/discussion was to add an API endpoint that used a simplified JSON Patch format, where the backend was responsible for building the appropriate JSON Patch requests before applying. We also looked into storing the datasets relationally but this forces us to define resources in a specific order where we lose flexibility, and adds complex reads to reassemble the data from 6-8 tables.  This is viewed as a large lift at this time, so we're going to focus on building an endpoint that supports incremental patch operations.

https://github.com/ethyca/fidesops/issues/1093
