### ISSUE TITLE
[Spike] Email server options (Timebox: 1 week)

### ISSUE THREAD

**Issue by adriaaaa** [ethyca/fidesops#983]
Research to identify email service options.

1. Is there a commonly used open source option?
2. How may we integrate with a service that mid-market customers are already using like [Twilio Sendgrid](https://www.twilio.com/sendgrid/email-api) or mailgun or google.
3.  If customers aren't using something like twilio, what may we, Ethyca, may be able to support to send emails.
4. Think about a local dev version that spins up a version in docker compose environment

Things to consider:
* local http/https conflicts
* how will we eventually support customizable email templates

The purpose of this research ticket is to investigate the above scenarios and document some ideas for solutions to help support features like an Email Connector, Subject Identity Verification, and Automated Subject Communications.

**Comment by eastandwestwind** [comment]
@adriaaaa I'd like to get additional product info on 2 things:
1) How do we anticipate a user to update email templates? Will it be manually in a template file, or eventually will there be UI? What would the UI roughly show?
2) What things will be editable in an email template? Colors? Subject Line? Body text?
3) Do we want to support a user using different email services for different purposes? E.g. Twilio for subject ID verification, and mailgun for email connector?
4) Can you describe more about the different purposes for our email server? I know you mentioned `Email Connector, Subject Identity Verification, and Automated Subject Communications`, but any additional details, particularly which purpose would be good for an MVP (highest priority?), and the acceptance criteria of each purpose would be super helpful.

Thanks so much!

**Comment by adriaaaa** [comment]
@eastandwestwind 

1. I anticipate that we will need a UI to help companies to modify the template and/or preview what the emails will look like. I would say the priority is for us to just provide a default email template as the minimum required (if we need to cut some scope from this quarter) for this feature but in the future organizations will ask how they could modify/preview it. The design team has a [figma](https://www.figma.com/file/4qxuluEzDsfOGY1tTw8YYe/Subject-Identity-Verification?node-id=14%3A5744) file they are brainstorming on if you want to check it out.
2. Yes colors, subject line, body text, font style, font size
3. Good question, that may be the case in the future for larger orgs, but let's limit it to one for now
4. I'll slack you the confluence docs for those features where you can find some requirements there. The highest priority is the Subject Identity Verification one.

**Comment by seanpreston** [comment]
Thanks for the valuable session there @eastandwestwind, I've added some follow-up tickets:
- [Tests for the email config APIs](https://github.com/ethyca/fidesops/issues/1086)
- [Remove org. name from designs](https://github.com/ethyca/fidesops/issues/1087)
- [Add Mailgun email tasks to a separate celery queue](https://github.com/ethyca/fidesops/issues/1088)
